apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-config-data
  namespace: other-project-workloads
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Mi