apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: other-root-app
  namespace: argocd
spec:
  project: other-project
  source:
    repoURL: https://github.com/BlacksQare/k3s-test.git
    targetRevision: master
    path: argocd/applications/other-project
  destination:
    server: https://kubernetes.default.svc
    namespace: other-project-workloads
  syncPolicy:
    automated:
      prune: true
      selfHeal: true